spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC
      username: root
      password: tmy20020217
      initial-size: 10
      max-active: 20
      max-wait: 500
      min-idle: 5

server:
  port: 80

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
